id = "pug-zed-extension"
name = "Pug/Jade"
version = "0.0.1"
schema_version = 1
authors = ["Raul Pavel <raul.pavel20@gmail.com>"]
description = "Pug/Jade language support for Zed"
repository = "https://github.com/raulpavel20/pug-zed-extension"

[grammars.pug]
repository = "https://github.com/zealot128/tree-sitter-pug"
commit = "a7ff31a38908df9b9f34828d21d6ca5e12413e18"
